gui:
  scrollHeight: 10
  showListFooter: false
  showBottomLine: false
git:
  log:
    order: "date-order"
  autoFetch: false
  autoRefresh: false
  branchLogCmd: "git log --color=always --abbrev-commit --decorate --pretty=medium {{branchName}} --"
  allBranchesLogCmds:
    - git log --all --color=always --abbrev-commit --decorate --pretty=medium
  pagers:
    - pager: delta --paging=never
      colorArg: always
