"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[ ](bg:color_orange)\
$character\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$haskell\
$python\
[](fg:color_blue bg:color_bg3)\
$docker_context\
[](fg:color_bg3 bg:none)\
[ ]()\
$line_break"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg0 = '#282828'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_orange = '#d65d0e'
color_yellow = '#d79921'

[directory]
style = "fg:color_bg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 1

[git_branch]
symbol = ""
style = "fg:color_bg0 bg:color_aqua"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:color_bg0 bg:color_aqua"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "fg:color_fg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[c]
symbol = " "
style = "fg:color_fg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "fg:color_fg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "fg:color_fg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "fg:color_fg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "fg:color_fg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[docker_context]
symbol = ""
style = "fg:#83a598 bg:color_bg3"
format = '[ $symbol( $context) ]($style)'

[line_break]
disabled = false

[character]
disabled = false
format = "$symbol"
success_symbol = '[ ](bold bg:color_orange fg:color_bg0)'
error_symbol = '[ !](bold bg:color_orange fg:color_bg0)'
